import type { Metadata } from "next";
import getConfig from 'next/config';
import "./globals.css";
import Script from "next/script";

const { publicRuntimeConfig } = getConfig();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}
      <Script id="gtag">
        {`
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', '${publicRuntimeConfig.measurementId}');
        `}
      </Script>
      <Script
        strategy="afterInteractive"
        src={`https://www.googletagmanager.com/gtag/js?id=${publicRuntimeConfig.measurementId}`}
      />
      </body>
    </html>
  );
}
